# -*- coding: utf-8 -*-
"""manual_berry

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1699oqjTAEe7N5_zc8XKU79ZuURoHqGaW
"""

import datetime
import sys
import numpy as np
import IMU

# Sensitivity scale factors (based on datasheet)
ACC_SCALE = 0.061 * 0.00981  # mg/LSB to m/s²
GYRO_SCALE = 8.75 * 0.0000174533  # mdps/LSB to rad/s
MAG_SCALE = 0.08 * 0.1  # mGauss/LSB to μT

IMU.detectIMU()
if IMU.BerryIMUversion == 99:
    print("No BerryIMU found... exiting")
    sys.exit()
IMU.initIMU()

print("Listening for fall events...")

while True:
    # Read sensor values
    current_data = {
        'Acceleration X': IMU.readACCx() * ACC_SCALE,
        'Acceleration Y': IMU.readACCy() * ACC_SCALE,
        'Acceleration Z': IMU.readACCz() * ACC_SCALE,
        'Angular Velocity X': IMU.readGYRx() * GYRO_SCALE,
        'Angular Velocity Y': IMU.readGYRRy() * GYRO_SCALE,
        'Angular Velocity Z': IMU.readGYRz() * GYRO_SCALE,
    }

    # Check fall conditions
    if (
        current_data['Acceleration X'] < -20.0 or
        current_data['Acceleration Y'] > 10.0 or
        current_data['Acceleration Z'] > 15.0 or
        current_data['Angular Velocity X'] < -2.0 or
        current_data['Angular Velocity Y'] < -3.0 or
        current_data['Angular Velocity Z'] > 1.0
    ):
        print("Fall detected!")
        print("Current Data:", current_data)
        break