# -*- coding: utf-8 -*-
"""fall detection receiver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwDNSNSJWa8C6Y14Dn1ISuDZ-uzD9cWY
"""

import socket
import json

# UDP Setup
UDP_IP = "0.0.0.0"  # Listen on all available interfaces
UDP_PORT = 5001     # Ensure this matches the sender's port

# Create a UDP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

print("Waiting for fall detection data...")

try:
    while True:
        # Receive data
        data, addr = sock.recvfrom(1024)

        try:
            # Decode and parse JSON
            json_data = json.loads(data.decode('utf-8'))

            # Extract fall detection status
            fall_detected = json_data.get("fallDetected", False)
            print(f"Fall detected: {fall_detected} from {addr}")

        except json.JSONDecodeError:
            print(f"Invalid data received from {addr}: {data.decode('utf-8')}")

except KeyboardInterrupt:
    print("Receiver stopped.")

finally:
    sock.close()
