# -*- coding: utf-8 -*-
"""sternum_IMU_receiver

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1is34k5ujZPNaO-eYeY4KRPTAlvIlDAF1
"""

import socket
import json

# UDP Setup
UDP_IP = "0.0.0.0"  # Listen on all available interfaces
UDP_PORT_f = 5001     # fall detection port
UDP_PORT_s = 5005     # step counter detection port

# Create a UDP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT_f))
sock.bind((UDP_IP, UDP_PORT_s))

print("Waiting for IMU sternum data...")

try:
    while True:
        # Receive data
        data, addr = sock.recvfrom(1024)

        try:
            # Decode and parse JSON
            json_data = json.loads(data.decode('utf-8'))

            # Extract fall detection status
            fall_detected = json_data.get("fallDetected", False)
            print(f"Fall detected: {fall_detected} from {addr}")

              # Extract the step count
            step_count = json_data.get("stepCount", 0)
            print(f"Received step count: {step_count} from {addr}")

        except json.JSONDecodeError:
            print(f"Invalid data received from {addr}: {data.decode('utf-8')}")

except KeyboardInterrupt:
    print("Receiver stopped.")

finally:
    sock.close()